name: Bug report
description: Report something that is broken or incorrect
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include enough detail for us to reproduce.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - backend
        - frontend/dashboard
        - contracts
        - sdk
        - docs
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, browser, node version, wallet, chain
